import { Component, OnInit } from '@angular/core';
import { MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';
import { SubscriptionUpdateInfo } from 'src/app/models/backend-update/subscription-update';
import { LanguageService } from 'src/app/services/visitor-services/language.service';
import { AppConstant } from 'src/app/config/app-constant';
@Component({
    selector: 'app-term-and-condition-popup',
    templateUrl: './term-and-condition-popup.component.html',
    styleUrls: ['./term-and-condition-popup.component.css']
})
export class TermAndConditionPopupComponent implements OnInit {

    constructor(private languageService: LanguageService, public dialogRef: MatDialogRef<TermAndConditionPopupComponent>) { }

    ngOnInit(): void {
    }
    onClick(): void {

        this.dialogRef.close();
    }
    uiLabels: any = this.languageService.getUiLabels(AppConstant.COMP.TERMSANDCONDITION_POPUP, AppConstant.UI_LABEL_TEXT);
    // uiLabels =
    //     {
    //         "iagree": "I Agree",
    //         "cancel": " Cancel",
    //         "termsConditionTitle": "Terms and Condition",
    //         "termsConditionContent": "      Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information."

    //     };


}
